version: "3"

services: 
    profiles_project:
        build:
            context: .
        #ports: 
        #    - "8000:8000"
        expose:
            - 8000
        volumes: 
            - static_volume:/vol/web/static
        command: >
            sh -c "python manage.py wait_for_db &&
                  python manage.py migrate --no-input &&
                  python manage.py collectstatic --no-input &&
                  gunicorn profiles_project.wsgi --bind 0.0.0.0:8000"
# python manage.py runserver 0.0.0.0:8000"                  
        environment: 
            - DB_HOST=db
            - DB_NAME=profiles_project
            - DB_USER=postgres
            - DB_PASS=supersecretpassword
        depends_on: 
            - db
        restart: always
    
    db:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment: 
            - POSTGRES_DB=profiles_project
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=supersecretpassword
        restart: always
    nginx:
        build: ./nginx        
        volumes:
            - static_volume:/vol/web/static
        ports:
            - 1337:80
        depends_on:
            - profiles_project
        restart: always
volumes:    
    static_volume:
    postgres_data: